# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            NTNU LRA
tagline:          'A Jekyll theme'
description:      "Legged Robots for the Arctic and beyond lab"
url:              https://ntnu-lra.github.io
baseurl:          /

author:
  name:           'Kostas Alexis'
  url:            github.com/kostas-alexis

paginate:         5

header_pages:
  - index.md
  - team/index.md
  - robots/index.md
  - results/index.md