# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            NTNU LRA
tagline:          'Legged Robots for the Arctic and Beyond Lab'
description:      "Legged Robots for the Arctic and beyond lab"
url:              https://ntnu-lra.github.io
baseurl:          /

author:
  name:           'Kostas Alexis'
  url:            https://github.com/kostas-alexis

paginate:         5

# Navigation for the sidebar
header_pages:
  - index.md         # Home page
  - team/index.md    # Team page in the 'team' folder
  - robots/index.md  # Robots page in the 'robots' folder
  - results/index.md # Results page in the 'results' folder
