# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            NTNU LRA
tagline:          'Legged Robots for the Arctic & beyond Lab'
description:      "Legged Robots for the Arctic & beyond lab"
url:              https://ntnu-lra.github.io
baseurl:          /

author:
  name:           'Kostas Alexis'
  url:            https://github.com/kostas-alexis

paginate:         5

# Disable GitHub project link
github_project: false

# Remove version display
version: false

# Remove download link
download_link: false

# Navigation for the sidebar
header_pages:
  - index.md         # Home page
  - team/team.md    # Team page in the 'team' folder
  - robots/robots.md  # Robots page in the 'robots' folder
  - results/results.md # Results page in the 'results' folder
